"""
test_auto_artifact_downstream.py

Tests whether calc_expr / llm nodes can correctly read artifacts generated by
tool nodes in auto-artifact mode (no "product" dict → keys saved as
"{node_id}.{field}").

Uses only pubchem_get_basic_properties (client-side, no ORCA) so the test is
fast and offline-friendly.

Plan structure:
  pubchem_ethanol   [tool, auto-artifact]  → ethanol.mw, ethanol.formula, ...
  pubchem_acetone   [tool, auto-artifact]  → acetone.mw, ...
  mw_sum            [calc_expr]            → needs ethanol.mw + acetone.mw

Usage:
  python test_auto_artifact_downstream.py
"""

from __future__ import annotations

import asyncio
import json
import os
import sys
import time

from dotenv import load_dotenv
load_dotenv(os.environ.get("ENV_FILE", ".env"))

from build_graph_from_plan import build_graph_from_plan, build_state
from client_helpers import state_get_tool_args, run_tool_node
from test_success_rate import CLIENT_SIDE_TOOL_FUNCS, EMPTY_STATE

# ── plan ──────────────────────────────────────────────────────────────────────

PLAN = {
    "user_text": "Get MW of ethanol and acetone; compute their sum.",
    "name": "test_auto_artifact_downstream",
    "version": "1.3",
    "geom_ids": [],
    "artifacts_to_save": [],
    "settings": {},
    "nodes": [
        {
            "id": "pubchem_ethanol",
            "kind": "tool",
            "tool": "pubchem_get_basic_properties",
            "needs": [],
            "args": {"name": "ethanol"},
            "expect": {"mw": {"type": "float"}},
        },
        {
            "id": "pubchem_acetone",
            "kind": "tool",
            "tool": "pubchem_get_basic_properties",
            "needs": [],
            "args": {"name": "acetone"},
            "expect": {"mw": {"type": "float"}},
        },
        {
            "id": "mw_sum",
            "kind": "calc_expr",
            "needs": ["pubchem_ethanol", "pubchem_acetone"],
            "needs_artifacts": ["pubchem_ethanol.mw", "pubchem_acetone.mw"],
            "expr": "pubchem_ethanol_mw + pubchem_acetone_mw",
            "product": {"mw_sum": "value"},
        },
    ],
    "final_report": {
        "format": "markdown",
        "fields": [
            "pubchem_ethanol.mw",
            "pubchem_acetone.mw",
            "mw_sum",
        ],
    },
}

ETHANOL_MW = 46.07   # g/mol
ACETONE_MW = 58.08
TOL = 0.5            # tolerance for float comparison

# ── runner ────────────────────────────────────────────────────────────────────

async def run_plan(plan: dict) -> dict:
    graph = build_graph_from_plan(
        plan,
        get_tool_args=state_get_tool_args,
        run_tool_node=run_tool_node,
    )
    state = build_state(plan, dict(EMPTY_STATE), client_side_tools=CLIENT_SIDE_TOOL_FUNCS)
    result = await graph.ainvoke(state)
    return result


def main():
    print("=" * 60)
    print("  Auto-artifact downstream test")
    print("=" * 60)
    print(f"\nPlan: {PLAN['name']}")
    print("Tool nodes (auto-artifact, no product dict):")
    print("  pubchem_ethanol → pubchem_ethanol.mw, pubchem_ethanol.formula, ...")
    print("  pubchem_acetone → pubchem_acetone.mw, ...")
    print("calc_expr node:")
    print("  mw_sum: needs_artifacts=[pubchem_ethanol.mw, pubchem_acetone.mw]")
    print("          expr=pubchem_ethanol_mw + pubchem_acetone_mw")
    print()

    t0 = time.monotonic()
    result = asyncio.run(run_plan(PLAN))
    elapsed = time.monotonic() - t0

    artifacts = result.get("artifacts", {})
    run_log   = result.get("run_log", [])

    print(f"Elapsed: {elapsed:.1f}s")
    print()
    print("Artifacts in final state:")
    for k, v in sorted(artifacts.items()):
        print(f"  {k}: {v!r}")

    print()
    print("Run log (node outcomes):")
    for entry in run_log:
        nid    = entry.get("node_id", "?")
        status = entry.get("status", "?")
        err    = entry.get("error", "")
        print(f"  {nid}: {status}" + (f"  [{err}]" if err else ""))

    # ── checks ────────────────────────────────────────────────────────────────
    checks = {}

    # 1. auto-artifact keys exist
    checks["ethanol_mw_present"]  = "pubchem_ethanol.mw" in artifacts
    checks["acetone_mw_present"]  = "pubchem_acetone.mw" in artifacts

    # 2. values are plausible (PubChem returns mw as string)
    eth_mw = artifacts.get("pubchem_ethanol.mw")
    ace_mw = artifacts.get("pubchem_acetone.mw")
    try:
        checks["ethanol_mw_correct"] = abs(float(eth_mw) - ETHANOL_MW) < TOL
    except (TypeError, ValueError):
        checks["ethanol_mw_correct"] = False
    try:
        checks["acetone_mw_correct"] = abs(float(ace_mw) - ACETONE_MW) < TOL
    except (TypeError, ValueError):
        checks["acetone_mw_correct"] = False

    # 3. calc_expr downstream node ran and produced correct sum
    # mw_sum is written via product mapping; read from final_report which consolidates all outputs
    fr = result.get("final_report") or {}
    mw_sum = artifacts.get("mw_sum") or fr.get("mw_sum")
    try:
        expected_sum = float(eth_mw) + float(ace_mw)
    except (TypeError, ValueError):
        expected_sum = None
    checks["mw_sum_present"]  = mw_sum is not None
    checks["mw_sum_correct"]  = (
        isinstance(mw_sum, (int, float)) and expected_sum is not None
        and abs(mw_sum - expected_sum) < TOL
    )

    # 4. no node errored
    checks["no_errors"] = all(
        e.get("status") != "error" for e in run_log
    )

    print()
    print("Checks:")
    all_pass = True
    for k, v in checks.items():
        tag = "PASS" if v else "FAIL"
        print(f"  [{tag}] {k}")
        if not v:
            all_pass = False

    print()
    if all_pass:
        print("RESULT: PASS — calc_expr correctly reads auto-artifact keys.")
    else:
        print("RESULT: FAIL — downstream node could not read auto-artifact keys.")
        sys.exit(1)


if __name__ == "__main__":
    main()
